requires "Kossy", 0.38;

#requires "Starlet", 0.25;
requires "Gazelle", 0.30;

requires "Plack::Middleware::Session::Simple";
requires "Cache::Memcached::Fast";
requires "Sereal";

requires "DBIx::Sunny";
requires "DBD::mysql";

requires "Log::Minimal";
requires "DBIx::QueryLog";
